// This file is generated by Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow that suggests relevant knowledge base articles based on a ticket's subject and description.
 *
 * - suggestKnowledgeBaseArticles - A function that suggests knowledge base articles.
 * - SuggestKnowledgeBaseArticlesInput - The input type for the suggestKnowledgeBaseArticles function.
 * - SuggestKnowledgeBaseArticlesOutput - The return type for the suggestKnowledgeBaseArticles function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestKnowledgeBaseArticlesInputSchema = z.object({
  subject: z.string().describe('The subject of the ticket.'),
  description: z.string().describe('The description of the ticket.'),
});
export type SuggestKnowledgeBaseArticlesInput = z.infer<typeof SuggestKnowledgeBaseArticlesInputSchema>;

const SuggestKnowledgeBaseArticlesOutputSchema = z.object({
  articles: z
    .array(z.string())
    .describe(
      'A list of relevant knowledge base articles based on the ticket subject and description.'
    ),
});
export type SuggestKnowledgeBaseArticlesOutput = z.infer<typeof SuggestKnowledgeBaseArticlesOutputSchema>;

export async function suggestKnowledgeBaseArticles(
  input: SuggestKnowledgeBaseArticlesInput
): Promise<SuggestKnowledgeBaseArticlesOutput> {
  return suggestKnowledgeBaseArticlesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestKnowledgeBaseArticlesPrompt',
  input: {schema: SuggestKnowledgeBaseArticlesInputSchema},
  output: {schema: SuggestKnowledgeBaseArticlesOutputSchema},
  prompt: `You are a help desk assistant. Based on the subject and description of the support ticket, suggest relevant knowledge base articles that might help the user resolve their issue. Return a list of article titles.

Subject: {{{subject}}}
Description: {{{description}}}`,
});

const suggestKnowledgeBaseArticlesFlow = ai.defineFlow(
  {
    name: 'suggestKnowledgeBaseArticlesFlow',
    inputSchema: SuggestKnowledgeBaseArticlesInputSchema,
    outputSchema: SuggestKnowledgeBaseArticlesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
